/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MustachioImport } from './routes/mustachio'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MustachioRoute = MustachioImport.update({
  id: '/mustachio',
  path: '/mustachio',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/mustachio': {
      id: '/mustachio'
      path: '/mustachio'
      fullPath: '/mustachio'
      preLoaderRoute: typeof MustachioImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mustachio': typeof MustachioRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mustachio': typeof MustachioRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/mustachio': typeof MustachioRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mustachio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mustachio'
  id: '__root__' | '/' | '/mustachio'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MustachioRoute: typeof MustachioRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MustachioRoute: MustachioRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/mustachio"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/mustachio": {
      "filePath": "mustachio.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
