name: Pull Request

on: pull_request

permissions:
  contents: write

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Commit changes if any
        uses: EndBug/add-and-commit@v9

      - name: Approve pull request
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --auto --sqaush ${{ github.event.pull_request.html_url }}
